export const viteTestEnv: Record<string, string> = {
  VITE_GATEWAY_URL: "http://localhost:5188",
  VITE_CHAT_SESSION_STORAGE_KEY: "vb-chat-session",
  VITE_APP_NAME: "Voice",
  VITE_NAV_ITEMS: "home|Home|home|dashboard;chat|Chat|chat|chat;voice|Voice|ai-spark|voice;data|Your data|shield|data",
  VITE_NAV_OWNER_ITEMS: "admin|Admin|settings|admin",
  VITE_ADMIN_NAV_ITEMS:
    "overview|Overview|dashboard|admin;conversations|Conversations|history|adminConversations;people|People|users|adminPeople;persona|Persona|spaces|adminPersona;deletions|Deletions|shield|adminDeletions",
  VITE_ADMIN_APP_ITEMS: "app|Home|home|dashboard",
  VITE_SIGNOUT_LABEL: "Sign out",
  VITE_LOADING_LABEL: "Loading…",
  VITE_SIGNIN_CONTINUE: "Continue with Google",
  VITE_NOT_OWNER_MESSAGE: "This account is not an owner.",
  VITE_SIGNIN_TITLE_CHAT: "Chat",
  VITE_SIGNIN_BODY_CHAT: "Sign in with Google to talk to the persona.",
  VITE_SIGNIN_TITLE_VOICE: "Voice",
  VITE_SIGNIN_BODY_VOICE: "Sign in with Google to talk to the persona.",
  VITE_SIGNIN_TITLE_PERSONA: "Persona",
  VITE_SIGNIN_BODY_PERSONA: "Sign in with Google to manage the persona.",
  VITE_SIGNIN_TITLE_ADMIN: "Admin",
  VITE_SIGNIN_BODY_ADMIN: "Sign in with Google to manage the persona.",
  VITE_SIGNIN_TITLE_APP: "Sign in",
  VITE_SIGNIN_BODY_APP: "Sign in with Google to continue.",
  VITE_INSIGHTS_RANGE_LABELS: "today|Today;7d|7 days;30d|30 days",
  VITE_INSIGHTS_DEFAULT_RANGE: "7d",
  VITE_INSIGHTS_DEFAULT_BUCKET: "day",
  VITE_LATENCY_BUDGET_FIRST_WORD_MS: "4000",
  VITE_FILTER_ANY: "*",
  VITE_CHANNEL_FILTERS: "*|All;text|Chat;voice|Voice",
  VITE_STAGE_LABELS: "stt_ms|STT;brain_ms|Brain;reframe_first_token_ms|First word;tts_first_byte_ms|TTS",
  VITE_BRAIN_MODE_LABELS: "retrieve|Retrieve;chat|Chat;unrecorded|Unrecorded;mixed|Mixed",
  VITE_KPI_CALLS_LABEL: "Calls",
  VITE_KPI_TURNS_LABEL: "Turns",
  VITE_KPI_FIRST_WORD_LABEL: "Median first word",
  VITE_KPI_ERROR_RATE_LABEL: "Error rate",
  VITE_KPI_CALLS_ICON: "history",
  VITE_KPI_TURNS_ICON: "chat",
  VITE_KPI_FIRST_WORD_ICON: "dashboard",
  VITE_KPI_ERROR_RATE_ICON: "shield",
  VITE_GRAPH_TURNS_LABEL: "Turns",
  VITE_GRAPH_SESSIONS_LABEL: "Calls",
  VITE_EMPTY_RANGE: "No activity in this range.",
  VITE_EMPTY_LIST: "No conversations yet.",
  VITE_EMPTY_TRANSCRIPT: "This conversation has no spoken turns.",
  VITE_EMPTY_MEMORY: "Nothing stored about you yet.",
  VITE_FETCH_ERROR: "Could not load this view.",
  VITE_RETRY_LABEL: "Retry",
  VITE_LOAD_MORE_LABEL: "Load more",
  VITE_SESSION_ENDED_LABEL: "Ended",
  VITE_SESSION_OPEN_LABEL: "Open",
  VITE_SUBSCRIPTION_NOTE:
    "Subscription is recorded for visibility. It is not an access gate.",
  VITE_SUBSCRIPTION_NONE: "none",
  VITE_MS_UNIT: "ms",
  VITE_SECOND_UNIT: "s",
  VITE_PERCENT_UNIT: "%",
  VITE_AUDIO_ABSENT: "No audio stored for this turn.",
  VITE_AUDIO_USER_LABEL: "You",
  VITE_AUDIO_BOT_LABEL: "Persona",
  VITE_AUDIO_DIRECTION_USER: "user",
  VITE_AUDIO_DIRECTION_BOT: "bot",
  VITE_REASONS_LABEL: "Reasons",
  VITE_ACTION_LABEL: "Action",
  VITE_LATENCY_LABEL: "Timings",
  VITE_MEMORY_REFS_LABEL: "Memory refs",
  VITE_CORRELATION_LABEL: "Trace id",
  VITE_BACK_LABEL: "Back",
  VITE_MEMORY_PANEL_TITLE: "What it remembers about you",
  VITE_MEMORY_PANEL_UNAVAILABLE:
    "Memory is unavailable right now. Your history is still here.",
  VITE_MEMORY_PANEL_ENABLED: "true",
  VITE_PEOPLE_TITLE: "People",
  VITE_WAITLIST_PATH: "/waitlist",
  VITE_WAITLIST_TITLE: "You're on the waitlist",
  VITE_WAITLIST_BODY: "Access is granted by the owner. You do not have a member account yet.",
  VITE_ACCESS_ACTIVE: "active",
  VITE_ACCESS_WAITLISTED: "waitlisted",
  VITE_ACCESS_DENIED: "denied",
  VITE_ACCESS_REVOKED: "revoked",
  VITE_ACCESS_CONSENT: "consent",
  VITE_ACCESS_DENIED_TITLE: "Access denied",
  VITE_ACCESS_DENIED_BODY: "This account was not approved.",
  VITE_ACCESS_REVOKED_TITLE: "Access revoked",
  VITE_ACCESS_REVOKED_BODY: "This account can no longer use the product.",
  VITE_WAITLIST_QUEUE_TITLE: "Waitlist",
  VITE_WAITLIST_APPROVE_LABEL: "Approve selected",
  VITE_WAITLIST_DENY_LABEL: "Deny selected",
  VITE_WAITLIST_REVOKE_LABEL: "Revoke",
  VITE_WAITLIST_EMPTY_QUEUE: "No pending requests.",
  VITE_WAITLIST_SELECTED_NONE: "Select at least one request.",
  VITE_ACCESS_QUEUE_STATUS: "requested",
  VITE_ACCESS_ACTION_APPROVE: "approve",
  VITE_ACCESS_ACTION_DENY: "deny",
  VITE_ACCESS_ACTION_REVOKE: "revoke",
  VITE_CONVERSATIONS_TITLE: "Conversations",
  VITE_OVERVIEW_ACTIVITY_TITLE: "Activity",
  VITE_OVERVIEW_LATENCY_TITLE: "Latency",
  VITE_OVERVIEW_BUDGET_LABEL: "Budget",
  VITE_RECENT_TITLE: "Recent",
  VITE_QUOTA_TITLE: "Daily limits",
  VITE_QUOTA_HELP: "0 turns a cap off. Changes apply on the next turn. Owner accounts are not capped.",
  VITE_QUOTA_TURNS_LABEL: "Turns per day",
  VITE_QUOTA_MINUTES_LABEL: "Voice minutes per day",
  VITE_QUOTA_TIMEZONE_LABEL: "Timezone",
  VITE_QUOTA_WARN_LABEL: "Warn ratio",
  VITE_QUOTA_SAVE_LABEL: "Save limits",
  VITE_QUOTA_SAVED: "Saved.",
  VITE_CONSENT_PATH: "/consent",
  VITE_PRIVACY_PATH: "/privacy",
  VITE_TERMS_PATH: "/terms",
  VITE_DATA_PATH: "/dashboard/data",
  VITE_ADMIN_DELETIONS_PATH: "/admin/deletions",
  VITE_PRIVACY_TITLE: "Privacy",
  VITE_PRIVACY_BODY: "We store conversation text, session metadata, and private memories so the persona can remember you. Audio blobs are stored only when archiving is on.",
  VITE_TERMS_TITLE: "Terms",
  VITE_TERMS_BODY: "Use of this service is by invitation. You can export or delete your data from Your data.",
  VITE_CONSENT_TITLE: "Before you continue",
  VITE_CONSENT_BODY: "Please accept the current privacy policy and terms. This does not create an account until access is granted.",
  VITE_CONSENT_PRIVACY_LABEL: "I have read and accept the",
  VITE_CONSENT_TERMS_LABEL: "I have read and accept the",
  VITE_CONSENT_ACCEPT_LABEL: "Accept and continue",
  VITE_COOKIE_NOTICE_BODY: "This app uses a signed session cookie after you sign in with Google.",
  VITE_COOKIE_NOTICE_ACCEPT: "Got it",
  VITE_COOKIE_STORAGE_KEY: "vb-cookie-notice",
  VITE_COOKIE_STORAGE_VALUE: "1",
  VITE_DATA_TITLE: "Your data",
  VITE_DATA_HELP: "Export a copy of what we store, or erase it.",
  VITE_DATA_EXPORT_TITLE: "Export",
  VITE_DATA_EXPORT_BODY: "Download transcripts, session metadata, and remembered facts.",
  VITE_DATA_EXPORT_LABEL: "Download my data",
  VITE_DATA_EXPORT_DONE: "Download started.",
  VITE_DATA_DELETE_TITLE: "Delete my data",
  VITE_DATA_DELETE_BODY: "This removes your conversations, audio, private memories, and member account. Your waitlist row stays so a later sign-in can start empty.",
  VITE_DATA_DELETE_HINT: "Type DELETE MY DATA to confirm.",
  VITE_DATA_DELETE_PENDING: "A deletion request is already waiting for the owner.",
  VITE_DATA_CONFIRMATION_LABEL: "Confirmation",
  VITE_DATA_DELETE_NOW_LABEL: "Delete now",
  VITE_DATA_REQUEST_LABEL: "Ask the owner to delete",
  VITE_DATA_CANCEL_REQUEST_LABEL: "Cancel request",
  VITE_DATA_OWNER_PROTECTED: "Owner accounts cannot be deleted from this page.",
  VITE_EXPORT_FILENAME: "voice-bot-export.json",
  VITE_LIFECYCLE_DELETE_CONFIRMATION: "DELETE MY DATA",
  VITE_LIFECYCLE_ACTION_REQUEST: "request",
  VITE_LIFECYCLE_ACTION_COMPLETE: "complete",
  VITE_LIFECYCLE_ACTION_CANCEL: "cancel",
  VITE_DELETION_QUEUE_STATUS: "pending",
  VITE_DELETIONS_TITLE: "Deletions",
  VITE_DELETIONS_QUEUE_TITLE: "Pending deletions",
  VITE_DELETIONS_HELP: "Completing a request erases that member. Type DELETE MY DATA to complete.",
  VITE_DELETIONS_COMPLETE_LABEL: "Complete selected",
  VITE_DELETIONS_CANCEL_LABEL: "Cancel selected",
  VITE_DELETIONS_EMPTY_QUEUE: "No pending deletions.",
  VITE_DELETIONS_SELECTED_NONE: "Select at least one request.",
};
