export const viteTestEnv: Record<string, string> = {
  VITE_GATEWAY_URL: "http://localhost:5188",
  VITE_CHAT_SESSION_STORAGE_KEY: "vb-chat-session",
  VITE_VOICE_WS_PATH: "/ws/voice",
  VITE_PERSONA_ID_QUERY: "persona_id",
  VITE_TURN_SPEAKER_USER: "user",
  VITE_TURN_SPEAKER_PERSONA: "persona",
  VITE_APP_NAME: "Voice",
  VITE_NAV_ITEMS: "home|Home|home|dashboard;chat|Chat|chat|chat;voice|Voice|ai-spark|voice;data|Your data|shield|data",
  VITE_NAV_OWNER_ITEMS: "admin|Admin|settings|admin",
  VITE_ADMIN_NAV_ITEMS:
    "overview|Overview|dashboard|admin;conversations|Conversations|history|adminConversations;people|People|users|adminPeople;persona|Persona|spaces|adminPersona;deletions|Deletions|shield|adminDeletions",
  VITE_ADMIN_APP_ITEMS: "app|Home|home|dashboard",
  VITE_SIGNOUT_LABEL: "Sign out",
  VITE_LOADING_LABEL: "Loading…",
  VITE_SIGNIN_CONTINUE: "Continue with Google",
  VITE_NOT_OWNER_MESSAGE: "This account is not an owner.",
  VITE_SIGNIN_TITLE_CHAT: "Chat",
  VITE_SIGNIN_BODY_CHAT: "Sign in with Google to talk to the persona.",
  VITE_SIGNIN_TITLE_VOICE: "Voice",
  VITE_SIGNIN_BODY_VOICE: "Sign in with Google to talk to the persona.",
  VITE_SIGNIN_TITLE_PERSONA: "Persona",
  VITE_SIGNIN_BODY_PERSONA: "Sign in with Google to manage the persona.",
  VITE_SIGNIN_TITLE_ADMIN: "Admin",
  VITE_SIGNIN_BODY_ADMIN: "Sign in with Google to manage the persona.",
  VITE_SIGNIN_TITLE_APP: "Sign in",
  VITE_SIGNIN_BODY_APP: "Sign in with Google to continue.",
  VITE_INSIGHTS_RANGE_LABELS: "today|Today;7d|7 days;30d|30 days",
  VITE_INSIGHTS_DEFAULT_RANGE: "7d",
  VITE_INSIGHTS_DEFAULT_BUCKET: "day",
  VITE_LATENCY_BUDGET_FIRST_WORD_MS: "4000",
  VITE_FILTER_ANY: "*",
  VITE_CHANNEL_FILTERS: "*|All;text|Chat;voice|Voice",
  VITE_STAGE_LABELS: "stt_ms|STT;brain_ms|Brain;reframe_first_token_ms|First word;tts_first_byte_ms|TTS",
  VITE_BRAIN_MODE_LABELS: "retrieve|Retrieve;chat|Chat;unrecorded|Unrecorded;mixed|Mixed",
  VITE_KPI_CALLS_LABEL: "Calls",
  VITE_KPI_TURNS_LABEL: "Turns",
  VITE_KPI_FIRST_WORD_LABEL: "Median first word",
  VITE_KPI_ERROR_RATE_LABEL: "Error rate",
  VITE_KPI_CALLS_ICON: "history",
  VITE_KPI_TURNS_ICON: "chat",
  VITE_KPI_FIRST_WORD_ICON: "dashboard",
  VITE_KPI_ERROR_RATE_ICON: "shield",
  VITE_GRAPH_TURNS_LABEL: "Turns",
  VITE_GRAPH_SESSIONS_LABEL: "Calls",
  VITE_EMPTY_RANGE: "No activity in this range.",
  VITE_EMPTY_LIST: "No conversations yet.",
  VITE_EMPTY_TRANSCRIPT: "This conversation has no spoken turns.",
  VITE_EMPTY_MEMORY: "Nothing stored about you yet.",
  VITE_FETCH_ERROR: "Could not load this view.",
  VITE_RETRY_LABEL: "Retry",
  VITE_LOAD_MORE_LABEL: "Load more",
  VITE_SESSION_ENDED_LABEL: "Ended",
  VITE_SESSION_OPEN_LABEL: "Open",
  VITE_SUBSCRIPTION_NOTE:
    "Subscription is recorded for visibility. It is not an access gate.",
  VITE_SUBSCRIPTION_NONE: "none",
  VITE_MS_UNIT: "ms",
  VITE_SECOND_UNIT: "s",
  VITE_PERCENT_UNIT: "%",
  VITE_AUDIO_ABSENT: "No audio stored for this turn.",
  VITE_AUDIO_USER_LABEL: "You",
  VITE_AUDIO_BOT_LABEL: "Persona",
  VITE_AUDIO_DIRECTION_USER: "user",
  VITE_AUDIO_DIRECTION_BOT: "bot",
  VITE_REASONS_LABEL: "Reasons",
  VITE_ACTION_LABEL: "Action",
  VITE_LATENCY_LABEL: "Timings",
  VITE_MEMORY_REFS_LABEL: "Memory refs",
  VITE_CORRELATION_LABEL: "Trace id",
  VITE_BACK_LABEL: "Back",
  VITE_MEMORY_PANEL_TITLE: "What it remembers about you",
  VITE_MEMORY_PANEL_UNAVAILABLE:
    "Memory is unavailable right now. Your history is still here.",
  VITE_MEMORY_PANEL_ENABLED: "true",
  VITE_PEOPLE_TITLE: "People",
  VITE_WAITLIST_PATH: "/waitlist",
  VITE_WAITLIST_TITLE: "You're on the waitlist",
  VITE_WAITLIST_BODY: "Access is granted by the owner. You do not have a member account yet.",
  VITE_ACCESS_ACTIVE: "active",
  VITE_ACCESS_WAITLISTED: "waitlisted",
  VITE_ACCESS_DENIED: "denied",
  VITE_ACCESS_REVOKED: "revoked",
  VITE_ACCESS_CONSENT: "consent",
  VITE_ACCESS_DENIED_TITLE: "Access denied",
  VITE_ACCESS_DENIED_BODY: "This account was not approved.",
  VITE_ACCESS_REVOKED_TITLE: "Access revoked",
  VITE_ACCESS_REVOKED_BODY: "This account can no longer use the product.",
  VITE_WAITLIST_QUEUE_TITLE: "Waitlist",
  VITE_WAITLIST_APPROVE_LABEL: "Approve selected",
  VITE_WAITLIST_DENY_LABEL: "Deny selected",
  VITE_WAITLIST_REVOKE_LABEL: "Revoke",
  VITE_WAITLIST_EMPTY_QUEUE: "No pending requests.",
  VITE_WAITLIST_SELECTED_NONE: "Select at least one request.",
  VITE_ACCESS_QUEUE_STATUS: "requested",
  VITE_ACCESS_ACTION_APPROVE: "approve",
  VITE_ACCESS_ACTION_DENY: "deny",
  VITE_ACCESS_ACTION_REVOKE: "revoke",
  VITE_CONVERSATIONS_TITLE: "Conversations",
  VITE_OVERVIEW_ACTIVITY_TITLE: "Activity",
  VITE_OVERVIEW_LATENCY_TITLE: "Latency",
  VITE_OVERVIEW_BUDGET_LABEL: "Budget",
  VITE_OVERVIEW_HEALTH_TITLE: "Health",
  VITE_OVERVIEW_OPS_TITLE: "Alerts",
  VITE_OVERVIEW_OPS_EMPTY: "No alerts.",
  VITE_RECENT_TITLE: "Recent",
  VITE_QUOTA_TITLE: "Daily limits",
  VITE_QUOTA_HELP: "0 turns a cap off. Changes apply on the next turn. Owner accounts are not capped.",
  VITE_QUOTA_TURNS_LABEL: "Turns per day",
  VITE_QUOTA_MINUTES_LABEL: "Voice minutes per day",
  VITE_QUOTA_TIMEZONE_LABEL: "Timezone",
  VITE_QUOTA_WARN_LABEL: "Warn ratio",
  VITE_QUOTA_SAVE_LABEL: "Save limits",
  VITE_QUOTA_SAVED: "Saved.",
  VITE_CONSENT_PATH: "/consent",
  VITE_PRIVACY_PATH: "/privacy",
  VITE_TERMS_PATH: "/terms",
  VITE_STATUS_PATH: "/status",
  VITE_STATUS_API_PATH: "/api/status",
  VITE_DATA_PATH: "/dashboard/data",
  VITE_ADMIN_DELETIONS_PATH: "/admin/deletions",
  VITE_PRIVACY_TITLE: "Privacy",
  VITE_PRIVACY_BODY: "We store conversation text, session metadata, and private memories so the persona can remember you. Audio blobs are stored only when archiving is on.",
  VITE_TERMS_TITLE: "Terms",
  VITE_TERMS_BODY: "Use of this service is by invitation. You can export or delete your data from Your data.",
  VITE_STATUS_TITLE: "Status",
  VITE_STATUS_UPDATED: "Last checked",
  VITE_STATUS_COMPONENTS: "Systems",
  VITE_STATUS_INCIDENTS: "Past incidents",
  VITE_STATUS_EMPTY: "No incidents reported.",
  VITE_STATUS_LINK: "Status",
  VITE_CONSENT_TITLE: "Before you continue",
  VITE_CONSENT_BODY: "Please accept the current privacy policy and terms. This does not create an account until access is granted.",
  VITE_CONSENT_PRIVACY_LABEL: "I have read and accept the",
  VITE_CONSENT_TERMS_LABEL: "I have read and accept the",
  VITE_CONSENT_ACCEPT_LABEL: "Accept and continue",
  VITE_COOKIE_NOTICE_BODY: "This app uses a signed session cookie after you sign in with Google.",
  VITE_COOKIE_NOTICE_ACCEPT: "Got it",
  VITE_COOKIE_STORAGE_KEY: "vb-cookie-notice",
  VITE_COOKIE_STORAGE_VALUE: "1",
  VITE_DATA_TITLE: "Your data",
  VITE_DATA_HELP: "Export a copy of what we store, or erase it.",
  VITE_DATA_EXPORT_TITLE: "Export",
  VITE_DATA_EXPORT_BODY: "Download transcripts, session metadata, and remembered facts.",
  VITE_DATA_EXPORT_LABEL: "Download my data",
  VITE_DATA_EXPORT_DONE: "Download started.",
  VITE_DATA_DELETE_TITLE: "Delete my data",
  VITE_DATA_DELETE_BODY: "This removes your conversations, audio, private memories, and member account. Your waitlist row stays so a later sign-in can start empty.",
  VITE_DATA_DELETE_HINT: "Type DELETE MY DATA to confirm.",
  VITE_DATA_DELETE_PENDING: "A deletion request is already waiting for the owner.",
  VITE_DATA_CONFIRMATION_LABEL: "Confirmation",
  VITE_DATA_DELETE_NOW_LABEL: "Delete now",
  VITE_DATA_REQUEST_LABEL: "Ask the owner to delete",
  VITE_DATA_CANCEL_REQUEST_LABEL: "Cancel request",
  VITE_DATA_OWNER_PROTECTED: "Owner accounts cannot be deleted from this page.",
  VITE_EXPORT_FILENAME: "voice-bot-export.json",
  VITE_LIFECYCLE_DELETE_CONFIRMATION: "DELETE MY DATA",
  VITE_LIFECYCLE_ACTION_REQUEST: "request",
  VITE_LIFECYCLE_ACTION_COMPLETE: "complete",
  VITE_LIFECYCLE_ACTION_CANCEL: "cancel",
  VITE_DELETION_QUEUE_STATUS: "pending",
  VITE_DELETIONS_TITLE: "Deletions",
  VITE_DELETIONS_QUEUE_TITLE: "Pending deletions",
  VITE_DELETIONS_HELP: "Completing a request erases that member. Type DELETE MY DATA to complete.",
  VITE_DELETIONS_COMPLETE_LABEL: "Complete selected",
  VITE_DELETIONS_CANCEL_LABEL: "Cancel selected",
  VITE_DELETIONS_EMPTY_QUEUE: "No pending deletions.",
  VITE_DELETIONS_SELECTED_NONE: "Select at least one request.",
  VITE_PERSONA_VOICE_TTS_KEY: "tts_voice",
  VITE_PERSONA_VOICE_FISH_KEY: "fish_voice",
  VITE_PERSONA_VOICE_PROVIDER_KEY: "voice_provider",
  VITE_PERSONA_VOICE_PROVIDER_AURA: "aura",
  VITE_PERSONA_VOICE_PROVIDER_FISH: "fish",
  VITE_PERSONA_CATALOG_HELP:
    "Create or link Engram personas here. Drafts stay off the member list until you publish.",
  VITE_PERSONA_LIST_TITLE: "Catalog",
  VITE_PERSONA_LIST_EMPTY: "No personas recorded yet.",
  VITE_PERSONA_ADD_LABEL: "Add persona",
  VITE_PERSONA_CREATE_TITLE: "Create in Engram",
  VITE_PERSONA_CREATE_HELP:
    "Tries Engram create. If the key cannot manage the org, link an existing persona id instead.",
  VITE_PERSONA_CREATE_LABEL: "Create persona",
  VITE_PERSONA_CREATING_LABEL: "Creating…",
  VITE_PERSONA_LINK_TITLE: "Link existing",
  VITE_PERSONA_LINK_HELP: "Record an Engram persona id that already exists in the dashboard.",
  VITE_PERSONA_LINK_LABEL: "Link persona",
  VITE_PERSONA_LINKING_LABEL: "Linking…",
  VITE_PERSONA_CREATE_FORBIDDEN:
    "Engram refused create. Paste an existing persona id and link it.",
  VITE_PERSONA_SAVE_LABEL: "Save persona",
  VITE_PERSONA_SAVING_LABEL: "Saving…",
  VITE_PERSONA_SAVED: "Persona saved.",
  VITE_PERSONA_CREATED: "Persona created.",
  VITE_PERSONA_LINKED: "Persona linked.",
  VITE_PERSONA_PUBLISH_LABEL: "Publish",
  VITE_PERSONA_UNPUBLISH_LABEL: "Unpublish",
  VITE_PERSONA_PUBLISHED: "Persona published.",
  VITE_PERSONA_UNPUBLISHED: "Persona unpublished.",
  VITE_PERSONA_PUBLISHED_BADGE: "Published",
  VITE_PERSONA_DRAFT_BADGE: "Draft",
  VITE_PERSONA_UNPUBLISH_CONFIRM_TITLE: "Unpublish this persona?",
  VITE_PERSONA_UNPUBLISH_CONFIRM_BODY:
    "Members lose access immediately and a live call ends on its next reply. Nothing is deleted, and publishing again restores everything.",
  VITE_PERSONA_UNPUBLISH_CONFIRM_LABEL: "Unpublish",
  VITE_PERSONA_CONFIRM_CANCEL_LABEL: "Cancel",
  VITE_PERSONA_DESTROY_TITLE: "Destroy this persona",
  VITE_PERSONA_DESTROY_BODY:
    "This deletes what the persona knows and every member's private history with it, in Engram and here. It cannot be undone.",
  VITE_PERSONA_DESTROY_HINT: "Type the handle to confirm:",
  VITE_PERSONA_DESTROY_CONFIRM_LABEL: "Handle",
  VITE_PERSONA_DESTROY_LABEL: "Destroy persona",
  VITE_PERSONA_DESTROYING_LABEL: "Destroying…",
  VITE_PERSONA_DESTROYED: "Persona destroyed.",
  VITE_REQUEST_FAILED: "request failed",
  VITE_CALL_PHASE_IDLE: "Idle",
  VITE_CALL_PHASE_CONNECTING: "Connecting",
  VITE_CALL_PHASE_LISTENING: "Listening",
  VITE_CALL_PHASE_THINKING: "Thinking",
  VITE_CALL_PHASE_SPEAKING: "Speaking",
  VITE_CALL_PHASE_RECONNECTING: "Reconnecting",
  VITE_CALL_PHASE_ERROR: "Error",
  VITE_CALL_START_LABEL: "Start call",
  VITE_CALL_STARTING_LABEL: "Starting…",
  VITE_CALL_END_LABEL: "End call",
  VITE_CALL_MIC_LABEL: "Mic",
  VITE_CALL_SESSION_SAVED_BADGE: "Session saved",
  VITE_CALL_TRANSCRIPT_LISTENING: "Speak when the badge says Listening.",
  VITE_CALL_TRANSCRIPT_IDLE: "Start a call to see the live transcript.",
  VITE_CHAT_NEW_CONVERSATION_LABEL: "New conversation",
  VITE_CHAT_THINKING_LABEL: "Thinking…",
  VITE_CHAT_MESSAGE_LABEL: "Message",
  VITE_CHAT_SEND_LABEL: "Send",
  VITE_CHAT_SENDING_LABEL: "Sending…",
  VITE_PERSONA_HANDLE_LABEL: "Handle",
  VITE_PERSONA_NAME_LABEL: "Display name",
  VITE_PERSONA_DESCRIPTION_LABEL: "Description",
  VITE_PERSONA_ENGRAM_ID_LABEL: "Engram persona id",
  VITE_PERSONA_TTS_LABEL: "TTS voice id",
  VITE_PERSONA_TTS_HELP:
    "Deepgram voice id for this persona. The env voice is used only if this is empty.",
  VITE_PERSONA_FISH_LABEL: "Fish voice id",
  VITE_PERSONA_FISH_HELP:
    "Hosted Fish Audio voice id for this persona. Leave empty to keep Deepgram Aura.",
  VITE_PERSONA_PROVIDER_LABEL: "Spoken voice",
  VITE_PERSONA_PROVIDER_HELP:
    "Choose Deepgram Aura or Fish Audio. A Fish sitting is a later change; Aura calls still use Aura.",
  VITE_PERSONA_PROVIDER_AURA_LABEL: "Deepgram Aura",
  VITE_PERSONA_PROVIDER_FISH_LABEL: "Fish Audio",
  VITE_PERSONA_VOICE_JSON_LABEL: "Voice style (JSON)",
  VITE_PERSONA_VOICE_INVALID: "voice_config must be a JSON object",
  VITE_PERSONA_TEACH_TITLE: "Teach",
  VITE_PERSONA_TEACH_LABEL: "Fact",
  VITE_PERSONA_TEACH_BUTTON: "Teach fact",
  VITE_PERSONA_TEACHING_LABEL: "Teaching…",
  VITE_PERSONA_TAUGHT: "Fact taught.",
  VITE_PERSONA_QUESTIONS_TITLE: "Question bank",
  VITE_PERSONA_QUESTIONS_COVERAGE: "Coverage",
  VITE_PERSONA_QUESTIONS_EMPTY: "No open questions. Answer by key if you have one.",
  VITE_PERSONA_QUESTIONS_REFRESH: "Refresh",
  VITE_PERSONA_QUESTIONS_REFRESHED: "Questions refreshed.",
  VITE_PERSONA_QUESTIONS_KEY: "Question key",
  VITE_PERSONA_QUESTIONS_ANSWER: "Answer",
  VITE_PERSONA_QUESTIONS_SAVE: "Save answer",
  VITE_PERSONA_QUESTIONS_SAVED: "Answer saved.",
  VITE_PERSONA_QUESTIONS_USE_KEY: "Use key",
  VITE_PERSONA_INGEST_TITLE: "Shared document",
  VITE_PERSONA_INGEST_BUTTON: "Ingest document",
  VITE_PERSONA_INGESTING_LABEL: "Ingesting…",
  VITE_PERSONA_INGESTED: "Document ingested.",
  VITE_PERSONA_CLONE_TITLE: "Clone Fish voice",
  VITE_PERSONA_CLONE_HELP:
    "Upload a short clip. Fish stores the voice; we keep only the returned id. This is not a document for Engram.",
  VITE_PERSONA_CLONE_FILE_LABEL: "Voice clip",
  VITE_PERSONA_CLONE_ACCEPT: ".wav,.mp3,.m4a,.opus,.webm,.ogg",
  VITE_PERSONA_CLONE_BUTTON: "Clone Fish voice",
  VITE_PERSONA_CLONE_CLONING_LABEL: "Cloning…",
  VITE_PERSONA_CLONE_CLONED: "Fish voice cloned.",
  VITE_PERSONA_SUBSCRIBE_TITLE: "Subscribe tester",
  VITE_PERSONA_SUBSCRIBE_USER: "Email or user id",
  VITE_PERSONA_SUBSCRIBE_BUTTON: "Subscribe in Engram",
  VITE_PERSONA_SUBSCRIBED: "Tester subscribed.",
  VITE_PERSONA_SELECT_FIRST: "Select a persona first.",
  VITE_PERSONA_PICKER_TITLE: "Who do you want to talk to?",
  VITE_PERSONA_PICKER_EMPTY: "No published personas yet.",
  VITE_PERSONA_PICKER_HELP: "Pick one, then start the call. Hang up to switch.",
  VITE_PERSONA_PICKER_CHAT_HELP: "Pick one, then send a message. Start a new conversation to switch.",
  VITE_PERSONA_PICKER_HISTORY_HELP: "Pick one to see sittings and memory for that persona.",
  VITE_PERSONA_NEED_PICK: "Pick someone first.",
  VITE_PERSONA_CHAT_READY: "Say something. Memory stays with this persona.",
};
